languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Backlog Reviews"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[params.author]
  name = "Krauzer"
  image = "profile.png"
  headline = "Tech and gaming enthusiast"
  bio = "I love coffe, cats and anime"
  links = [
    { link = "https://backloggd.com/u/Krauzer" },
    { reddit = "https://www.reddit.com/user/lKrauzer" },
    { steam = "https://store.steampowered.com" },
    { youtube = "https://www.youtube.com/@lKrauzer" },
  ]
